language: node_js

node_js:
  - 12.18.1

cache:
  directories:
    - "node_modules"

#safelist
# branches:
#   only:
#   - dev

install:
  - npm install

script:
  # - echo "skipping tests"
  - npm start &
  - npm test

# after_success: npm run coverage